server:
  port: 8889
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/myhomemythird/JenkinsTest.git
          searchPaths: myMicroservice/my-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/